insert into category (name) values ('C');
insert into category (name) values ('C++');
insert into category (name) values ('Java');
insert into category (name) values ('Javascript');
insert into category (name) values ('SQL');
insert into category (name) values ('Python');
insert into category (name) values ('Artificial Intelligence');
insert into category (name) values ('Computer Graphics');
insert into category (name) values ('PHP');
insert into category (name) values ('CSS');
insert into category (name) values ('HTML');
insert into category (name) values ('Prolog');
insert into category (name) values ('GLSL');
insert into category (name) values ('OpenGL');
insert into category (name) values ('DirectX');
insert into category (name) values ('Vulkan');
insert into category (name) values ('Neural Networks');
